### ISSUE TITLE
Enhance bookmarking cog

### ISSUE THREAD

**Issue by ChrisLovering** [python-discord/sir-lancebot#640] opened 2021-03-26 16:44 UTC
## Description

When a really cool message is sent in the server, people want to bookmark it for future reference.
If many people want to bookmark the same message, the chat could be flooded with `.bm 1231231231313` calls.

We should add a way for users to also bookmark the same message as another user, without having to send another command.

## Reasoning

To reduce the amount of messages sent in a channel when many people are wanting to bookmark a message.

## Proposed Implementation

Add a reaction listener to the cog, so any users that react with the mail emoji will also have the message bookmarked for them

## Would you like to implement this yourself?

- [ ] I'd like to implement this feature myself
- [x] Anyone can implement this feature

**Comment by HassanAbouelela** [comment] 2021-03-26 16:46
Duplicate of #341 which has... gone very silent

**Closed** 2021-03-26 17:06 UTC
Labels: status: planning, type: feature
