### ISSUE TITLE
[`Suggestion`]: Dictionary Command.

### ISSUE THREAD

**Issue by DenseReptile** [python-discord/sir-lancebot#1044] opened 2022-03-02 15:23 UTC
## Description

A dictionary command, that's about it.

## Reasoning

As a small command for the added convenience of not having to search the definition of a word in a separate browser tab.

## Proposed Implementation

For the dictionary (API) to use, I suggest to either use Wiktionary (a Wikimedia Foundation project, parent of Wikipedia) or the Oxford Dictionary (which is what Google uses)

It should display multiple definitions, and optionally with examples of it being used in a sentence for extra clarity, displayed as text with formatting to make it a little bit easier to follow. For those with many definitions (and would take up significant screen real estate), it should either span across multiple pages that can be navigated through the use of buttons or to have a button to delete (🗑️) the given definitions.

## Would you like to implement this yourself?

- [ ] I'd like to implement this feature myself
- [x] Anyone can implement this feature

**Comment by HassanAbouelela** [comment] 2022-03-02 16:42
FWIW, you can already do this using the wolfram alpha command. For example: `.wolfram define hello` or `.wolfram short define hello`.

**Comment by MaskDuck** [comment] 2022-03-04 08:02
can i be assigned

**Comment by HassanAbouelela** [comment] 2022-03-06 00:10
The issue is not approved @MaskDuck (you can tell if it's approved when there's an `approved` label on it). I'm not sure if we need this given the wolfram command exists.

**Comment by MaskDuck** [comment] 2022-03-10 04:57
ok~

**Comment by D0rs4n** [comment] 2022-03-20 12:48
That's a duplicate of #917
Hence, I'm going to close this issue.

**Closed by D0rs4n** 2022-03-20 12:48 UTC
Labels: type: feature, status: planning, category: utilities
