### ISSUE TITLE
Build-Your-Own Ducky!

### ISSUE THREAD

**Issue by Shivansh-007** [python-discord/sir-lancebot#651] opened 2021-04-01 04:54 UTC
# Build-Your-Own Ducky!

Well by now you know what this issue is going to be about, so lemme just brief it to you - Duckies are lovely, so why not have a command which can:

 - Allow you to build a ducky image, with help of reactions, or maybe user input.
- Or make a random ducky for you, using vco's ducky algorithm.

## Allow users to build their ducky!

 So now let us get to the details of this, we would build embed pages for each of the layers, namely
 
 1. The duck itself (the outfits, or the colors)
 2. The beak 
 3. The wing
 4. Other accessories 
 
 We can get the assets from the [Python Discord PyWeek project](https://github.com/python-discord/aaaaAAAA/tree/main/assets/duck-builder).  The user would go through the pages one by one with the help of pagination (they could go back or even skip a layer). And click on the reaction according to the index of the item. This would then get stored and once the user reaches the end, the bot would add a reaction "✅", and if the user clicks on this then the bot would generate their ducky with the help of the options they select.

Uhh, to make this clear, let us go through a run-through. Say I selected the following options:
```python
{
		"outfit": "ninja", # The user could either use a reaction to choose the outfit or just input the color's RGB/hex.
		"accessories": {
				"hats": "mortarboard",
				"equipment": "lighsaber",
		},
		"beak": "ninja", # The user could either use a reaction to choose the outfit or just input the color's RGB/hex.
		"wing": "ninja", # The user could either use a reaction to choose the outfit or just input the color's RGB/hex.
}
```
Then I would get to the page where I would either press the "✅" or just go back and change a few of my options. (The users' options would be displayed here, so they could review them). After clicking the "✅", it would generate the ducky and send it in the chat!!!

## Procedurally Generated Ducks
Rather than users creating duckies on their own, few people are a bit lazy to do this and want to get a randomly generated ducky, for this we should have a command that procedurally generates these ducks from the same set of assets that are getting used for making your ducky command.

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

**Comment by Akarys42** [comment] 2021-04-01 07:35
Hello! 

I’m afraid we are currently not interested in putting a ducky generator in Sir Lancebot. We have other plans such as https://github.com/python-discord/site/issues/465 and other Super Secret Projects:tm:. 
In the future please coordinate with us before making everyone waste time.

**Comment by lemonsaurus** [comment] 2021-04-01 13:56
@Shivansh-007 This is a well-specified issue, thanks for opening it.

I think putting the build-your-own-ducky feature into the bot is a UX nightmare, but since we'll be doing that on the site in https://github.com/python-discord/site/issues/465, this will still be solved.

I do think we should put a simpler random duck feature into Sir Lancebot, though, so I'm opening a similar issue now that's a little smaller in scope. - See https://github.com/python-discord/sir-lancebot/issues/652

**Comment by Shivansh-007** [comment] 2021-04-01 14:13
Thanks @lemonsaurus, I will have a look at them and share my inputs.

Well for build-your-own-ducky feature, we discussed this a bit in #dev-contrib channel and sort of agreed of making an API, which would allow us to do this, this API would then be used on the site for python-discord/site#465, and for the this feature.

**Comment by Akarys42** [comment] 2021-04-01 16:49
Will be reopening this issue and marking it as deferred until quackstack is done. After that we can discuss if we want such a feature.

For the record, the current concerns about this feature would be the UX design and the fact that we would have to regenerate the ducky every time an option change which would hurt ratelimits, bandwidth and resources, we shall benchmark all of this. 

I still would like to raise a simple suggestion, maybe having a build your own duck is better in a web interface? We can’t always fit everything in a discord bot. That said, I’d still love to see some ducky related commands!

**Comment by lemonsaurus** [comment] 2021-04-01 17:02
This issue is a duplicate of https://github.com/python-discord/sir-lancebot/issues/652, and https://github.com/python-discord/sir-lancebot/issues/652 is the implementation we should go for. We don't need a ducky builder in the bot, we're gonna do that in the site.

**Closed by lemonsaurus** 2021-04-01 17:02 UTC
Labels: status: deferred, status: planning, type: feature
