### ISSUE TITLE
Catification

### ISSUE THREAD

**Issue by hypergamer80** [python-discord/sir-lancebot#692] opened 2021-04-19 14:59 UTC
## Description
We would like to see an addition to the Sir Lancebot commands: `.catify`. This would insert random ᓚᘏᗢ's into a message sent by the invoker of the command.

## Reasoning
This would be useful since it enhances the ᓚᘏᗢ cult.

## Would you like to implement this yourself?

- [ ] I'd like to implement this feature myself
- [x ] Anyone can implement this feature

**Comment by dawnofmidnight** [comment] 2021-04-19 15:00
#691 is the same thing/

**Comment by Kronifer** [comment] 2021-04-19 15:00
Yeah I kinda beat you to it

**Comment by janine9vn** [comment] 2021-04-19 15:00
I'm going to close this as it's a duplicate of #691. We can move discussion there.

**Comment by hypergamer80** [comment] 2021-04-19 15:01
got it.

**Closed by janine9vn** 2021-04-19 15:00 UTC
Labels: status: planning, type: feature
