### ISSUE TITLE
Increase the amount of information given in .issue/.pr commands

### ISSUE THREAD

**Issue by vcokltfre** [python-discord/sir-lancebot#714] opened 2021-04-30 17:18 UTC
## Description
Basically: remove the ability to have multiple issue/pr numbers and add additional info to the embed, such as the issue/pr author, since the automatic linking of issues everywhere (#642) means that it's not necessary anymore to have these commands separate, as they display the same info unless of course that is changed to display more info about it.

## Proposed Implementation
I do not have any specific implementation details in mind.

## Would you like to implement this yourself?

- [ ] I'd like to implement this feature myself
- [x] Anyone can implement this feature

**Comment by ChrisLovering** [comment] 2021-08-05 13:33
Duplicate of #788

**Closed by ChrisLovering** 2021-08-05 13:33 UTC
Labels: status: planning, type: feature
