### ISSUE TITLE
Help command doesn't subclass `HelpCommand`

### ISSUE THREAD

**Issue by n0Oo0Oo0b** [python-discord/sir-lancebot#1265] opened 2023-05-05 02:29 UTC
## Description

 Lancebot's [current help command](https://github.com/python-discord/sir-lancebot/blob/main/bot/exts/core/help.py#L512) doesn't subclass `HelpCommand`, unlike [Python's](https://github.com/python-discord/bot/blob/main/bot/exts/info/help.py#L167). The former should be changed to match the latter because subclassing `HelpCommand` is the preferred way of creating custom help commands.

## Reasoning

This wouldn't change anything for the end user, but internally, the bot will be able to do things like `ctx.send_help(ctx.command)`

## Proposed Implementation

Replace Lancebot's help command with Python's new help command.

## Additional Details

I think we should also consider moving the help command to bot-core instead because it is common functionality for all bots.

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

**Comment by n0Oo0Oo0b** [comment] 2023-05-05 02:34
[This comment](https://github.com/python-discord/sir-lancebot/blame/main/bot/exts/core/help.py#L1) also mentions that changes to Python's help command should also be applied here, but the changes in python-discord/bot#519 (which refactored Python's help command to subclass `HelpCommand`) hasn't made it to Lancebot yet.

**Comment by TizzySaurus** [comment] 2023-05-05 02:52
Isn't the real solution here having an integrated HelpCommand in bot-core that the two bots both use? Since I imagine the logic is extremely similar, if not the _exact_ same across the two bots. This is part of python-discord/bot-core#85. So I guess that's the real solution to this issue.

**Comment by eamanu** [comment] 2023-05-05 02:57
It's not a good idea have the same logic in two (or more) places, why don't move the logic to a common place? like a module?

**Comment by eamanu** [comment] 2023-05-05 02:58
Sorry, I didn't  read your comment @TizzySaurus well.  Yes, that is better.

**Comment by ChrisLovering** [comment] 2023-05-05 11:23
Duplicate of https://github.com/python-discord/sir-lancebot/issues/470

**Closed by ChrisLovering** 2023-05-05 11:23 UTC
Labels: type: feature, status: planning
