### ISSUE TITLE
Quackstack integration in lancebot

### ISSUE THREAD

**Issue by vcokltfre** [python-discord/sir-lancebot#693] opened 2021-04-19 17:47 UTC
## Description
The ability to run `.duck [manduck=False]` command to get a random duck or manduck, generated by quackstack.

## Reasoning
Quackstack is currently fairly inaccessible since it's pretty much just a raw API. One thing we can do to make it more accessible to everyone is to allow them to use it through lancebot to create their own duckies!

## Proposed Implementation
Unsure of exact implementation, but roughly:
- Make POST to quackstack to generate a random duck
- Send the returned image URL as an embed's image

## Would you like to implement this yourself?

- [x] I'd like to implement this feature myself
- [ ] Anyone can implement this feature

**Comment by vcokltfre** [comment] 2021-04-19 18:07
here's how it looks because I'm bored and decided to make it, but I'll wait for approval before PRing
![image](https://user-images.githubusercontent.com/16879430/115282785-7fdc7580-a142-11eb-8028-6de90b342028.png)

**Comment by Kronifer** [comment] 2021-04-19 19:03
I'm Kronifer [REDACTED], and I approve this PR :shipit: 👍🏼

**Comment by Shivansh-007** [comment] 2021-04-20 14:53
This is a duplicate of #652.

**Comment by vcokltfre** [comment] 2021-04-20 15:26
being able to merge 2 issues when :blobpain:

**Closed** 2021-04-27 19:57 UTC
Labels: status: planning, type: feature
